### ISSUE TITLE
Support des claviers physiques

### ISSUE THREAD

**Issue by sgigou** [sgigou/ibepo#38]
Pour iPad et iPad Pro

**Comment by Tumulte** [comment]
Je plussoi énormément. J’ai téléchargé l’application pour pouvoir utiliser mon clavier Bluetooth (je suis habitué à Azerty sur le clavier virtuel). J’espère que ça arrivera vite !

**Comment by sgigou** [comment]
C’est la fonctionnalité la plus demandée, donc ce sera la prochaine à sortir — avec d’autres correctifs, bien évidemment. Je bosse sur un autre projet pour l’instant, mais je donnerai des nouvelles dès que je me lancerai dans la prochaine version d’iBépo. Il faudra juste que je trouve un clavier physique, ou une manière d’en simuler un.

**Comment by Kikangh** [comment]
Bonjour, je viens de découvrir ton app iBépo en prêtant attention à ta signature après t’avoir répondu sur le forum.bepo.fr =» achat direct.

Je confirme l’intérêt du support du clavier physique sur iPad Pro. Je pratique la frappe en aveugle sur clavier physique ce qui est impossible à faire sur un clavier tactile.

Cela fait quelques années que je cherche une solution pour utiliser mes claviers custom :Planck ; ergodox ez; dactyl manuform  (programmables avec QMK) en bepo sur iPad Pro.

Si tu as besoin d’un testeur, ce sera avec plaisir. Reviens vers moi au besoin.

**Comment by sgigou** [comment]
> Bonjour, je viens de découvrir ton app iBépo en prêtant attention à ta signature après t’avoir répondu sur le forum.bepo.fr =» achat direct.
> 
> Je confirme l’intérêt du support du clavier physique sur iPad Pro. Je pratique la frappe en aveugle sur clavier physique ce qui est impossible à faire sur un clavier tactile.
> 
> Cela fait quelques années que je cherche une solution pour utiliser mes claviers custom :Planck ; ergodox ez; dactyl manuform (programmables avec QMK) en bepo sur iPad Pro.
> 
> Si tu as besoin d’un testeur, ce sera avec plaisir. Reviens vers moi au besoin.

Merci pour l’achat, et merci pour la proposition de test !

Effectivement, si tu as autant de claviers à disposition, ça m’aiderait beaucoup… Je te contacterai avec plaisir une fois que j’aurais une version prête à tester pour voir si tout fonctionne comme souhaité.

**Comment by sgigou** [comment]
Bon, mauvaise nouvelle : Apple ne semble pas avoir fourni de manière d’ajouter de dispositions à la liste des claviers physiques. Ils ont défini la leur et c’est tout. 😞

La seule alternative que je peux fournir en attendant qu’ils ouvrent la fonctionnalité (🤞) est [celle choisie par TextExpander](https://www.thoughtasylum.com/2017/09/24/TextExpander-and-External-Keyboards-on-iOS/). Je vais ajouter dans l’application conteneur une page blanche qui corrigera la frappe à la volée pour permettre de saisir du texte en Bépo. J’ajouterai également la possibilité de copier et effacer rapidement le contenu.

Ce n’est pas aussi bien que ce que j’aimerai faire, mais ça permettra de saisir de longs textes en bépo sur clavier physique.

**Comment by Kikangh** [comment]
Bonjour Steve, est-ce que la situation est toujours la même avec iOS/iPadOS 16 ?
