### ISSUE TITLE
iBépo non disponible sur l'app store Suisse

### ISSUE THREAD

**Issue by JLTastet** [sgigou/ibepo#58]
Bonjour,

Je souhaiterais utiliser iBépo sur mon iPad, mais malheureusement je n'arrive pas à le trouver sur l'app store lorsque le pays sélectionné est "Suisse". Serait-il possible d'élargir sa disponibilité aux autres pays francophones ? (voire globalement) 

Merci !

**Comment by ClemABT** [comment]
Il n’est pas non plus disponible sur l’App Store français, il doit y avoir un soucis.

**Comment by sgigou** [comment]
Bonjour,

Effectivement, il y a un problème avec l’application iBépo. Je cherche à le corriger, mais n’ai malheureusement pas d’ETA à fournir.

Je mettrai à jour cette issue dès que le problème sera corrigé.

Bonne journée !

**Comment by champagnealexandre** [comment]
Idem pour le Canada ! Non dispo ici aussi, malheureusement.

**Comment by Gabrielmetaxian** [comment]
Bonjour,

Toujours pas de solution depuis le mois de juin ?

**Comment by sgigou** [comment]
Malheureusement non. Il ne s’agit pas d’un problème technique, mais légal. J’ai bon espoir que ça évolue dans les jours qui viennent.

**Comment by soleromel** [comment]
Bonjour,

Avez vous des nouvelles d'Apple ? J'ai du repasser à l'azerty et je ne me sens pas bien, ma santé mentale décline... Sauvez-nous svp il nous faut le bépo :)

**Comment by sgigou** [comment]
iBépo est de retour ! Merci de votre patience ⌨️
